### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by ashu-22** [astorfi/TensorFlow-World#16]
$ git clone https://github.com/TensorFlow-World.git
Cloning into 'TensorFlow-World'...
remote: Not Found
fatal: repository 'https://github.com/TensorFlow-World.git/' not found

**Comment by astorfi** [comment]
I just ran the following command and it's working.
git clone https://github.com/astorfi/TensorFlow-World.git

**Comment by astorfi** [comment]
@ashu-22 You forgot to put **astorfi** in the URL!
Please use the command in the aforementioned comment and let me know if it's working.
Thanks

**Comment by ashu-22** [comment]
How Can you tell me specifically, What should you have done there?

**Comment by astorfi** [comment]
@ashu-22 : Open the terminal and type the following:
git clone https://github.com/astorfi/TensorFlow-World.git

**Comment by ashu-22** [comment]
bash: https://github.com/astorfi/TensorFlow-World.git: No such file or
directory
I have got some errors.

**Comment by ashu-22** [comment]
Have your saw that error's.

**Comment by astorfi** [comment]
Type the following:

**git clone https://github.com/astorfi/TensorFlow-World.git**

@ashu-22 Are you using Linux?
Why you simply don't fork the repository?
If you want to use it locally, why you don't simply download it?

**Comment by ashu-22** [comment]
No, I am using Windows.

**Comment by astorfi** [comment]
@ashu-22 So simply fork and download the repository please.

**Comment by ashu-22** [comment]
In Windows, I have got some issues that I already mentioned there.

**Comment by astorfi** [comment]
@ashu-22 Even downloading from GitHub? You do not need to use the terminal ... Only push the download link from the top of the repository page.

**Comment by ashu-22** [comment]
I already fork it.

**Comment by ashu-22** [comment]
No men, I never did that thing.I am going to try that approach again as you
write about it only I can push the download link from the top of the
repository.
