### ISSUE TITLE
RE: Policy regarding typos in codebase.

### ISSUE THREAD

**Issue by adyavanapalli** [astorfi/TensorFlow-World#25]
This issue is regarding your policy regarding typos in your codebase. Here is the relevant section in your [CONTRIBUTING.rst](https://github.com/astorfi/TensorFlow-World/blob/master/CONTRIBUTING.rst):
_For typos, please do not create a pull request. Instead, declare them in issues or email the repository owner._

I suggest this policy be revised as it creates an extra step for you, the maintainer of this repo. For example, here is your current process:
1. Contributor finds a typo.
2. Contributor opens an issue.
3. Repo owner reads the issue.
4. Repo owner decides to create a code change to fix the typo and pushes the change.

Here is the suggested process:
1. Contributor finds a typo.
2. Contributor creates a code change to fix the typo and creates a pull request
3. Repo owner decides to accept the pull request and merges the changes.

If typos can be discussed _within_ a pull request, I don't see the point for a contributor to create an issue and _then_ the repo owner creates a code change to fix the typo. I suggest using Github **Issues** to discuss lengthy proposals, but typos should be handled directly within a pull request. For example, see this [Contributing guide for Github's open source guide](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md).

**Comment by adyavanapalli** [comment]
This suggestion came about when trying to fix a typo, given in #24.

**Comment by astorfi** [comment]
@adyavanapalli Thank you so much for spending time and your consideration.
I will investigate it ASAP!

**Comment by adyavanapalli** [comment]
@astorfi Any updates?

**Comment by astorfi** [comment]
@adyavanapalli Thank you for your attention. We decided to leave the contribution policy as is for now! Thanks
