### ISSUE TITLE
TensorBoard

### ISSUE THREAD

**Issue by ebeyabraham** [astorfi/TensorFlow-World#26]
using `tensorboard --logdir="absolute/path/to/log_dir"` to run tensorboard seems to give an error. Removing the `=` solves the issue.

**Comment by astorfi** [comment]
@MrGrayCode What is the code you are using? What is the error and to what directory you are referring?

**Comment by ebeyabraham** [comment]
I was referring to the documentation at https://github.com/astorfi/TensorFlow-World/tree/master/docs/tutorials/1-basics/basic_math_operations

It says to run Tensorboard using `tensorboard --logdir="absolute/path/to/log_dir"` which does not work. Changing it to `tensorboard --logdir "absolute/path/to/log_dir"` works.
I am using Tensorflow 1.6.0

**Comment by astorfi** [comment]
@MrGrayCode Oh it might be related to the version differences. That you for pointing it out.
