### ISSUE TITLE
Typos in README.rst

### ISSUE THREAD

**Issue by guptarohit** [astorfi/TensorFlow-World#9]
There are several typing errors in the 'README.rst' file.

**Comment by astorfi** [comment]
Thank you so much for addressing the issues.

**Comment by astorfi** [comment]
The typos in README.rst document have been checked and resolved!

**Comment by stites** [comment]
You should also change the capitalized 'L's in TensorFLow to just read "TensorFlow" in the header.

**Comment by astorfi** [comment]
@stites Thank you so much for your attention.
